name: Detecting Biased Language
on: [push]

jobs:
  biased_lang:
    runs-on: ubuntu-latest
    name: Detecting Biased Language
    steps:
      - uses: actions/checkout@v2
      - id: pink-panther
        continue-on-error: true
        uses: splunk/pink-panther@main
        with:
          token: ${{secrets.GITHUB_TOKEN}}